"""renaming stat cols

Revision ID: 07dc822dcfbb
Revises: da9ace9fe191
Create Date: 2025-12-24 18:04:07.394965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07dc822dcfbb'
down_revision = 'da9ace9fe191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('typing_stats', schema=None) as batch_op:
        batch_op.alter_column('wpm',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('accuracy',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('chars_typed',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('duration_seconds',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('typing_stats', schema=None) as batch_op:
        batch_op.alter_column('duration_seconds',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('chars_typed',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('accuracy',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('wpm',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
