"""add leaderboard table

Revision ID: 6cff187fe547
Revises: ad16c5a65f12
Create Date: 2025-12-24 17:50:47.166190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cff187fe547'
down_revision = 'ad16c5a65f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wpm', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leaderboard_recorded_at'), ['recorded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leaderboard_recorded_at'))

    op.drop_table('leaderboard')
    # ### end Alembic commands ###
