"""renaming stat cols

Revision ID: da9ace9fe191
Revises: 6cff187fe547
Create Date: 2025-12-24 18:02:53.388427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da9ace9fe191'
down_revision = '6cff187fe547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('typing_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_seconds', sa.Integer(), nullable=False))
        batch_op.drop_column('time_spent_sec')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('typing_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_spent_sec', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('duration_seconds')

    # ### end Alembic commands ###
